/* GLYIV KABAR — newsletter content (carbon insights). Each article carries a
   moodHex that drives its accent, backdrop, and the mood-color companion orb. */
window.KABAR = [
  {
    slug: "cbam-eksportir-indonesia",
    topic: "Regulasi",
    mood: "#B0894F",
    title: "CBAM sudah berlaku. Ini artinya bagi eksportir Indonesia.",
    dek: "Sejak 1 Januari 2026, karbon punya harga di perbatasan Eropa. Bagi eksportir besi, baja, aluminium, semen, dan pupuk, setiap ton yang tak terukur adalah tarif yang bisa dihindari — atau pasar yang bisa hilang.",
    cover: "/lab/img/tambang-dan-logam.jpg",
    author: "Redaksi Glyiv",
    role: "Ditinjau terhadap dokumen EU DG TAXUD",
    read: 6,
    views: 4820, likes: 312,
    orb: "Tanya soal CBAM",
    blocks: [
      { t: "lead", x: "Selama bertahun-tahun, keunggulan biaya manufaktur Indonesia sebagian bertumpu pada energi murah berbasis batu bara. Mulai 2026, Uni Eropa mulai menagih selisih karbon itu di perbatasan lewat CBAM — dan aturan mainnya berubah untuk siapa pun yang mengekspor ke sana." },
      { t: "p", x: "CBAM (Carbon Border Adjustment Mechanism) bekerja sederhana: importir di UE harus membeli sertifikat sebanding dengan emisi yang tertanam dalam barang yang mereka impor <a data-cite=\"ec\">1</a>. Bila produsen tak bisa membuktikan intensitas karbonnya dengan data terverifikasi, nilai default yang dipakai cenderung <strong>tinggi</strong> — dan mahal." },
      { t: "pull", x: "Tanpa data karbon yang kredibel, komoditas Indonesia berisiko didiskon harga — atau kehilangan akses ke pasar premium." },
      { t: "stat", n: "1 Jan 2026", l: "EU CBAM masuk fase bayar (besi, baja, aluminium, semen, pupuk, listrik, hidrogen)", s: "European Commission, DG TAXUD" },
      { t: "p", x: "Yang sering terlewat: CBAM bukan sekadar biaya kepatuhan, tapi <strong>sinyal harga</strong>. Ia memberi tahu pembeli global mana pemasok yang siap masa depan rendah-karbon dan mana yang tidak. Eksportir yang bisa menunjukkan jejak karbon per produk — tertelusur, terverifikasi — justru mendapat keunggulan kompetitif baru." },
      { t: "h2", x: "Apa yang bisa dilakukan sekarang" },
      { t: "p", x: "Langkah pertama bukan membeli offset, tapi <strong>mengukur</strong>: memetakan emisi tertanam per lini produk dengan metodologi yang selaras standar global (GHG Protocol / ISO 14064), lalu memverifikasinya hingga bisa diaudit. Data itulah yang menurunkan tarif CBAM dan menjaga pintu pasar tetap terbuka." },
      { t: "bars", h: [0.4, 0.6, 0.5, 0.78, 0.66, 0.9], cap: "Ilustrasi: eksposur biaya CBAM naik seiring intensitas karbon per ton." },
    ],
    sources: [
      { a: "European Commission (2023). Carbon Border Adjustment Mechanism.", u: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en" },
      { a: "World Bank / NewClimate Institute (2023). Estimasi eksposur CBAM negara berkembang." },
    ],
  },
  {
    slug: "pohon-sebagai-aset",
    topic: "Offset",
    mood: "#1cae6b",
    title: "Kenapa sebuah pohon kini adalah aset yang bisa diaudit.",
    dek: "Offset karbon punya reputasi buruk — penuh 'kredit zombie' yang tak jelas asalnya. Tokenisasi aset pohon nyata mengubahnya: dari klaim di atas kertas menjadi bukti yang dipantau satelit dan tercatat di rantai.",
    cover: "/lab/img/reforestation.jpg",
    author: "Redaksi Glyiv",
    role: "Ditinjau terhadap standar VCMI/ICVCM & ERC-3643",
    read: 7,
    views: 6140, likes: 587,
    orb: "Tanya soal Tree Marketplace",
    blocks: [
      { t: "lead", x: "Masalah pasar offset bukan pada idenya — menanam dan menjaga pohon memang menyerap karbon. Masalahnya pada bukti. Terlalu banyak kredit dijual tanpa jaminan bahwa pohonnya nyata, hidup, dan tak dihitung dua kali." },
      { t: "p", x: "Studi independen menemukan mayoritas kredit hutan tertentu bermasalah — dari proyek lama yang di-recycle hingga klaim yang tak layak standar internasional. Akibatnya, pembeli serius jadi skeptis, dan istilah <em>'kredit zombie'</em> melekat pada seluruh kategori <a data-cite=\"cp\">1</a>." },
      { t: "pull", x: "Kami originate, bukan bridge. Aset pohon nyata + dMRV terverifikasi + token ter-izin — bukan spekulasi." },
      { t: "p", x: "Pendekatan Glyiv membalik urutannya. Setiap pohon dipantau lewat <strong>dMRV berbasis satelit</strong> (indeks kehijauan NDVI, tingkat kelangsungan), lalu serapan karbonnya ter-tokenisasi sebagai aset dunia-nyata (RWA) dengan standar <strong>ERC-3643</strong> — identitas on-chain, KYC/AML di level kontrak. Retirement bersifat satu-arah, mencegah double-counting, dan terekonsiliasi ke registri resmi." },
      { t: "stat", n: "NDVI 0.82", l: "Rata-rata kesehatan tegakan Mangrove Lantebung — dipantau, bukan diklaim", s: "Ilustrasi pilot · dMRV Glyiv" },
      { t: "h2", x: "Dari klaim ke bukti" },
      { t: "p", x: "Perbedaannya bukan pemasaran, tapi <strong>data lineage</strong>: siapa pun bisa menelusuri sebuah kredit hingga ke petak lahan, tanggal pemantauan, dan tanda tangan on-chain-nya. Itulah yang memisahkan offset yang bermakna dari yang sekadar menenangkan hati." },
    ],
    sources: [
      { a: "CarbonPlan (2022). Analisis kualitas kredit hutan." },
      { a: "ERC-3643 Association. The T-REX permissioned token standard.", u: "https://www.erc3643.org/" },
    ],
  },
  {
    slug: "ai-dari-menghitung-ke-memangkas",
    topic: "Teknologi",
    mood: "#1F7A6B",
    title: "AI dan karbon: dari sekadar menghitung, ke benar-benar memangkas.",
    dek: "Gelombang pertama perangkat karbon sibuk menghitung emisi. Gelombang berikutnya — agen AI — membaca data itu terhadap biaya, menemukan pemborosan yang tak disadari, lalu menutupnya.",
    cover: "/lab/img/satellite.jpg",
    author: "Redaksi Glyiv",
    role: "Ditinjau terhadap praktik industri 2026",
    read: 5,
    views: 3910, likes: 274,
    orb: "Tanya soal agen AI Glyiv",
    blocks: [
      { t: "lead", x: "Menghitung karbon itu perlu, tapi tidak cukup. Sebuah laporan emisi yang rapi tidak dengan sendirinya menghemat satu rupiah pun. Yang mengubah keadaan adalah ketika data karbon dibaca berdampingan dengan data biaya — dan sistem memberi tahu Anda persis di mana uang bocor." },
      { t: "p", x: "Di sinilah agen AI masuk. Alih-alih dashboard pasif, agen karbon menyerap data aktivitas (energi, invoice, rantai pasok), <strong>menandai anomali</strong>, dan menghubungkan intensitas karbon dengan pengeluaran — memunculkan pemborosan yang tenggelam dalam tagihan gabungan." },
      { t: "pull", x: "Berhenti menghitung karbon. Mulai memangkasnya." },
      { t: "stat", n: "10–20%", l: "Penghematan biaya operasi yang kerap terungkap dari efisiensi energi & dekarbonisasi pada lini tertentu", s: "Riset operasional industri (mis. McKinsey)" },
      { t: "p", x: "Contoh konkret: sebuah pendingin yang menyala boros di jam sepi tak akan pernah muncul sebagai baris anggaran tersendiri. Tapi ketika karbon dipetakan per fasilitas, per shift, pola itu terlihat — dan rekomendasi tindakannya jelas. Karbon menjadi lensa untuk efisiensi, bukan sekadar beban pelaporan." },
      { t: "bars", h: [0.9, 0.7, 0.55, 0.44, 0.35, 0.28], cap: "Ilustrasi: emisi (dan biaya) menurun saat rekomendasi agen diterapkan." },
    ],
    sources: [
      { a: "McKinsey & Company. Decarbonization and operational cost savings." },
      { a: "Analisis industri 2026: agen AI dalam akuntansi karbon (Persefoni, CO2 AI, Watershed)." },
    ],
  },
];
